kind: ConfigMap
apiVersion: v1
metadata:
  name: events-cm
  namespace: events
data:
  RMQ_USER: admin
  RMQ_PASS: admin
  RMQ_HOST: { RABBITMQ_URL } # chenge_me
  RMQ_PORT: 5672
  MESSAGE_QUEUE: events.logs
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rabbitmq-cm
  namespace: events
data:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: admin
